[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino

upload_speed = 115200
monitor_speed = 115200
; upload_port = /dev/ttyUSB0  ; ESP32 NodeMCU port

lib_deps =
    waspinator/AccelStepper@^1.64